name: llms-in-medicine
channels:
  - conda-forge
dependencies:
  - _r-mutex=1.0.1
  - annotated-types=0.7.0
  - anyio=4.8.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - cctools_osx-arm64=1010.6
  - certifi=2024.12.14
  - cffi=1.17.1
  - clang=19.1.7
  - clang-19=19.1.7
  - clang_impl_osx-arm64=19.1.7
  - clang_osx-arm64=19.1.7
  - clangxx=19.1.7
  - clangxx_impl_osx-arm64=19.1.7
  - clangxx_osx-arm64=19.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=19.1.7
  - compiler-rt_osx-arm64=19.1.7
  - contourpy=1.3.1
  - curl=8.11.1
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - distro=1.9.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - gfortran_impl_osx-arm64=13.2.0
  - gfortran_osx-arm64=13.2.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.7
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=10.2.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - isl=0.26
  - jedi=0.19.2
  - jinja2=3.1.5
  - jiter=0.8.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libcurl=8.11.1
  - libcxx=19.1.7
  - libcxx-devel=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-arm64=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libpng=1.6.45
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - llvm-tools=19.1.7
  - llvm-tools-19=19.1.7
  - lxml=5.3.0
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.7.1
  - numpy=2.2.1
  - openai=1.59.7
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.1
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.5
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyparsing=3.2.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - r-base=4.1.3
  - r-boot=1.3_28.1
  - r-class=7.3_22
  - r-cluster=2.1.4
  - r-codetools=0.2_19
  - r-foreign=0.8_84
  - r-kernsmooth=2.23_21
  - r-lattice=0.21_8
  - r-lme4=1.1_33
  - r-mass=7.3_58.3
  - r-matrix=1.5_4.1
  - r-mgcv=1.8_42
  - r-minqa=1.2.4
  - r-nlme=3.1_162
  - r-nloptr=2.0.3
  - r-nnet=7.3_19
  - r-rcpp=1.0.10
  - r-rcppeigen=0.3.3.9.3
  - r-recommended=4.1
  - r-rpart=4.1.19
  - r-spatial=7.3_16
  - r-statmod=1.5.0
  - r-survival=3.5_5
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - sigtool=0.1.3
  - simplegeneric=0.8.1
  - six=1.17.0
  - sniffio=1.3.1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tapi=1300.6.5
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - tzlocal=5.2
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - anthropic==0.45.2
      - charset-normalizer==3.4.1
      - pymer4==0.8.2
      - requests==2.32.3
      - rpy2==3.5.17
      - urllib3==2.3.0
